config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  scope '(:locale)', locale: /en|zh-TW/ do
    root "pages#index"
    get "about"       => "pages#about"
    get "promotions"  => "event_categories#index"
    get "test"        => "pages#notify"
    get "search_product"      => "products#index"
    get "search_article"      => "articles#index"
    get "search_event"        => "events#index"

    resources :users

    resources :messages, only: [:new, :create]
    get "contact"   => "messages#new"

    resources :prod_categories, only: [:index, :show] do
      resources :products, only: [:show]
    end

    resources :blog_categories, only: [:index, :show] do
      resources :articles, only: [:show]
    end

    resources :event_categories, only: [:index, :show] do
      resources :events, only: [:show]
    end

    resources :comments, :notifications, :atm_payment_infos
    resources :orders, path_names: { new: 'checkout' }
    resources :carts, only: [:index]
    resources :order_items, only: [:create, :update, :destroy]
  end

  namespace :admin do
    root to: "orders#index"

    resources :prod_categories do
      resources :products
    end

    resources :blog_categories do
      resources :articles
    end

    resources :event_categories do
      resources :events
    end

    resources :company_profiles, :home_pages, :users, :orders
    resources :terms_of_services, :comments, :company_infos
  end

end

app/views/layouts/shared/_account_menu.html.erb
<div class="col-md-3">
  <aside class="left-shop">
    <div class="shop-categories mb30">
      <h1 class="asidetitle">會員中心</h1>
      <ul>
        <li><%= link_to "修改會員資料", edit_user_registration_path %></li>
        <li><%= link_to '我的訂單', orders_path %></li>
        <% if current_user.admin? %>
        <li><%= link_to 'Allpay post info', test_path %></li>
        <% end %>
      </ul>
    </div>
  </aside>
</div>

app/views/layouts/shared/_allpay_atm.html.erb
  <% payment_service_for  @order,
                          @order.user.email,
                          :service => :allpay,
                          :html    => { :id => 'allpay-atm-form', :method => :post } do |service| %>
    <% service.merchant_trade_no SecureRandom.hex(4) %>     <!-- X廠商交易編號 -->
    <% service.merchant_trade_date Time.now.strftime('%Y/%m/%d %H:%M:%S') %>      <!-- X廠商交易時間 -->
    <% service.total_amount @order.total.to_i %>      <!-- X交易金額 -->
    <% service.description @order.order_number %>       <!-- X交易描述 -->
    <% service.item_name getItemName(@order) %>     <!-- X商品名稱 -->
    <% service.choose_payment ActiveMerchant::Billing::Integrations::Allpay::PAYMENT_ATM %>     <!-- 選擇預設付款方式 -->
    <% service.return_url url_for(:only_path => false, :controller => 'account' , :action => 'notify') %>       <!-- X付款完成通知回傳網址 -->     
    <% service.client_back_url order_url @order  %>
    <% service.add_field("PaymentInfoURL" , url_for(:only_path => false , :controller => 'account' , :action => 'paymentInfoATM'))%>
    <% service.encrypted_data %><!-- X檢查碼 -->
    <%= submit_tag 'Buy!' %>
  <% end %>

app/views/layouts/shared/_mobile_version_cart.html.erb
<div class="mobile-version">
	<div class="cart-icon">
		<%= link_to carts_path do %><i class="fa fa-shopping-cart fa-3"></i><% end %>
		<span><%= current_cart.order_items.sum(:quantity) %></span> 個商品
	</div>
</div>

app/views/layouts/shared/empty.html.erb
<%= yield %>