config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  scope '(:locale)', locale: /en|zh-TW/ do
    root "pages#index"
    get "about"       => "pages#about"
    get "promotions"  => "event_categories#index"
    get "test"        => "pages#notify"
    get "search_product"      => "products#index"
    get "search_article"      => "articles#index"
    get "search_event"        => "events#index"

    resources :users

    resources :messages, only: [:new, :create]
    get "contact"   => "messages#new"

    resources :prod_categories, only: [:index, :show] do
      resources :products, only: [:show]
    end

    resources :blog_categories, only: [:index, :show] do
      resources :articles, only: [:show]
    end

    resources :event_categories, only: [:index, :show] do
      resources :events, only: [:show]
    end

    resources :comments, :notifications, :atm_payment_infos
    resources :orders, path_names: { new: 'checkout' }
    resources :carts, only: [:index]
    resources :order_items, only: [:create, :update, :destroy]
  end

  namespace :admin do
    root to: "orders#index"

    resources :prod_categories do
      resources :products
    end

    resources :blog_categories do
      resources :articles
    end

    resources :event_categories do
      resources :events
    end

    resources :company_profiles, :home_pages, :users, :orders
    resources :terms_of_services, :comments, :company_infos
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :orders
  has_many :authorizations, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  def admin?
  	self.admin == true
	end       

  def check_vip
    if 1 == self.id
      "<span class='blink' title='ˊ_>ˋy━･~...' >V V I P</span>"
    else
      "一般會員"
    end
  end
	
	# def self.from_omniauth(auth)
	#   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	#     user.email = auth.info.email
	#     user.password = Devise.friendly_token[0,20]
	#     user.name = auth.info.name   # assuming the user model has a name
	#     user.image = auth.info.image # assuming the user model has an image
	#   end
	# end	

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s).first_or_initialize
    # new record
    if authorization.user.blank?
    	# check if already reg. 
      user = User.where('email = ?', auth["info"]["email"]).first
      if user.blank?
	      user = User.new
	      user.password = Devise.friendly_token[0,10]
	      user.name = auth.info.name
	      user.email = auth.info.email
	      user.skip_confirmation!
	      user.save      
     	end

      authorization.user_id = user.id
      authorization.save
    end

  	authorization.user
  end	

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
  	@users = User.all.page(params[:page])
  end

  def show
  end

  def new
  end

  def edit
  end

  def update
  	@user = User.find(params[:id])
  	@user.toggle!(:admin)
  	respond_to do |format|
		  format.js {render inline: "location.reload();" }
		end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/shared/_common_js.html.erb
  <script src="/js/jquery.min.js"></script>
  <script type="text/javascript" src="/js/jquery-ui.js"></script>

  <script type="text/javascript" src="/js/jquery.superfish.js"></script>
  <script type="text/javascript" src="/js/jquery.bxslider.js"></script>

  <script type="text/javascript" src="/js/bootstrap.js"></script>
  <script type="text/javascript" src="/js/retina-1.1.0.min.js"></script>
  <script type="text/javascript" src="/js/jquery.nicescroll.min.js"></script>
  <script type="text/javascript" src="/js/jquery.isotope.min.js"></script>
  <script type="text/javascript" src="/js/jquery.imagesloaded.min.js"></script>
  <script type="text/javascript" src="/js/jquery.appear.js"></script>
  <script type="text/javascript" src="/js/jquery.countTo.js"></script>
  <script src="/js/jquery.easypiechart.js"></script>
  <!-- jQuery KenBurn Slider  -->
  <script type="text/javascript" src="/js/jquery.themepunch.revolution.min.js"></script>
  <script type="text/javascript" src="/js/script.js"></script>

app/views/users/shared/_links.html.erb
<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "以 #{provider.to_s.titleize} 登入", omniauth_authorize_path(resource_name, provider), class: "btn btn-primary btn-block" %><br />
  <% end -%>
<% end -%>

<%- if controller_name != 'sessions' %>
  <%= link_to "會員登入", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "註冊", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "忘記密碼？", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <!-- <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br /> -->
  <%= link_to "沒有收到驗證帳號的電子郵件？", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>