config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  scope '(:locale)', locale: /en|zh-TW/ do
    root "pages#index"
    get "about"       => "pages#about"
    get "promotions"  => "event_categories#index"
    get "test"        => "pages#notify"
    get "search_product"      => "products#index"
    get "search_article"      => "articles#index"
    get "search_event"        => "events#index"

    resources :users

    resources :messages, only: [:new, :create]
    get "contact"   => "messages#new"

    resources :prod_categories, only: [:index, :show] do
      resources :products, only: [:show]
    end

    resources :blog_categories, only: [:index, :show] do
      resources :articles, only: [:show]
    end

    resources :event_categories, only: [:index, :show] do
      resources :events, only: [:show]
    end

    resources :comments, :notifications, :atm_payment_infos
    resources :orders, path_names: { new: 'checkout' }
    resources :carts, only: [:index]
    resources :order_items, only: [:create, :update, :destroy]
  end

  namespace :admin do
    root to: "orders#index"

    resources :prod_categories do
      resources :products
    end

    resources :blog_categories do
      resources :articles
    end

    resources :event_categories do
      resources :events
    end

    resources :company_profiles, :home_pages, :users, :orders
    resources :terms_of_services, :comments, :company_infos
  end

end

app/models/order.rb
class Order < ActiveRecord::Base
  # paginates_per 2

  belongs_to :order_status
  belongs_to :cart
  belongs_to :user
  belongs_to :payment
  # before_create :set_order_status_and_fee
  # before_save :finalize
  validates_presence_of :name, :cellphone, :address
  validates :cellphone, format: { with: /\A(\d{10})\z/ }
  # before_save :
  # t.decimal  "subtotal",        precision: 10
  # t.decimal  "shipping_fee",    precision: 10
  # t.decimal  "total",           precision: 10
  # t.integer  "order_status_id", limit: 4
  # t.integer  "user_id",         limit: 4
  # t.string   "name",            limit: 255
  # t.string   "phone",           limit: 255
  # t.string   "address",         limit: 255
  # t.string   "order_number",    limit: 255
  # t.integer  "cart_id",         limit: 4

  # def subtotal
  	# 當購物車是空的時候，返回0
  	# order_items.collect { |item| item.valid? ? item.unit_price*item.quantity : 0 }.sum
  # end

  # def user_info(user)
  #   self.update_attributes(user_id: user.id, name: user.name)
  # end

  def self.check_atm_timeout
    where(order_status_id: 5).each do |order|
      info = AtmPaymentInfo.find_by_merchant_trade_no(order.merchant_trade_no)
      order.update_attributes(order_status_id: 4) if Time.now > info.expire_date
    end 
  end

  def pending?
    self.order_status_id == 1 || self.order_status_id == 5
  end

  def paid?
    self.order_status_id == 2
  end

  def shipped?
    self.order_status_id == 3
  end

  def has_order_no?
    self.order_status_id == 2
  end

  def color_merchant_trade_no
    if self.paid? || self.shipped?
      y = "<strong class='text-primary'>#{self.merchant_trade_no[0..3]}</strong> "
      md = "<strong class='text-danger'>#{self.merchant_trade_no[4..7]}</strong> "
      hms = "<strong class='text-success'>#{self.merchant_trade_no[8..13]}</strong> "
      n_6_digit = "<strong class='text-warning'>#{self.merchant_trade_no[14..19]}</strong>"
      str = y+md+hms+n_6_digit
    end
  end

  def cart_item_name
    str = ''
    cart.order_items.each do |item|
      str+="#{item.product.name}x#{item.quantity}#"
    end
    str
  end

  def add_cart_info(cart)
    self.cart_id = cart.id
    self.subtotal = cart.order_items.sum(:total_price)
    self.shipping_fee = TermsOfService.last.shipping_fee
    self.total = subtotal + shipping_fee
    self.order_status_id = 1
    # self.order_number = Time.now.strftime("%Y%m%d%H%M%S%3N")
  end

  def get_payment_info
    AtmPaymentInfo.find_by_merchant_trade_no(self.merchant_trade_no)
    # AtmPaymentInfo.where(merchant_trade_no: self.merchant_trade_no).last
  end

  def get_payment_time
    Notification.find_by_merchant_trade_no(self.merchant_trade_no).payment_date    
  end

  def cancel
    self.order_status_id == 1 ? update_attributes(order_status_id: 4) : false
  end

  private

  	# def set_order_status_and_fee
  	# 	self.order_status_id = 1 # In progress
   #    self.shipping_fee = TermsOfService.last.shipping_fee
  	# end

  	# def update_subtotal
  	# 	self[:subtotal] = subtotal
  	# end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

	# 1 = 尚未付款
	# 2 = 已付款
	# 3 = 已出貨
	# 4 = 取消訂單
	# 5 = 取號成功
  def index
  	case params[:status]
	  	when 'pending_orders'
	  		@orders = Order.where(order_status_id: [1, 5]).order(id: :desc).page(params[:page])
	  	when 'paid_orders'
	  		@orders = Order.where(order_status_id: 2).order(id: :desc).page(params[:page])
	  	when 'shipped_orders'
	  		@orders = Order.where(order_status_id: 3).order(id: :desc).page(params[:page])
	  	when 'cancel_orders'
	  		@orders = Order.where(order_status_id: 4).order(id: :desc).page(params[:page])
	  	else
	  		@orders = Order.all.order(id: :desc).page(params[:page])
  	end  	
  end

  def show
  	@order = Order.find(params[:id])
  end

  def update
  	@order = Order.find(params[:id])

  	case params[:change_status]
	  	when 'shipped'
	  		@order.update_attributes(order_status_id: 3)
	  	when 'paid'
	  		@order.update_attributes(order_status_id: 2)
	  	when 'cancel'
	  		@order.update_attributes(order_status_id: 4)
  	end

  	respond_to do |format|
		  format.js {render inline: "location.reload();" }
		end  	
  end

  def new
  end

  def edit
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :ensure_order_has_item, only: [:new, :create]
	before_action :authenticate_user!	    
	# before_action :own_order, only: [:edit, :update]  

  def index
    @orders = valid_order.order(id: :desc).page(params[:page])
  end

  def new
    @order = current_user.orders.new
  end

  def create
    @order = current_user.orders.new(order_params_on_create)
    @order.add_cart_info(current_cart)
    if @order.save
      OrderMailer.pending(@order).deliver
      session[:cart_id] = nil
      flash[:placed_order] = '訂單建立成功！感謝您的購買，歡迎您再次蒞臨！'
      redirect_to @order
    else
      render 'new'
    end
  end

  def show
    @order = valid_order.find_by_id(params[:id])
    redirect_to root_url unless @order

    # 產生結帳表單
    if @order.order_status_id == 1
      get_checkout_params(@order) 
    end

    # 產生ATM匯款資訊
    if @order.order_status_id == 5
      @order_payment_info = @order.get_payment_info
    end

  end

  def update
    order = current_user.orders.find_by_id(params[:id])
    if order && order.cancel
      flash[:cancel_order_result] = "訂單已成功取消！"
    else
      flash[:cancel_order_result] = "無效的操作！"
    end
    redirect_to :back
  end

  private

  	def ensure_order_has_item	
  		if current_cart.order_items.empty?
  			flash[:empty_cart] = "請選購商品後再進行結帳！"
  			redirect_to carts_url
  		end
  	end

    def order_params_on_create
      params.require(:order).permit(:name, :cellphone, :address, :payment_id)
    end

  	def order_params_on_update
  		params.require(:order).permit(:merchant_trade_no)
  	end

    def valid_order
      current_user.orders.where(order_status: (1..5).to_a)
    end

    def get_checkout_params(order)
      client = Allpay::Client.new(mode: :production)
      payment_type = %w[Credit WebATM ATM]

      # 不論選擇哪種結帳方式都需要傳送的欄位
      fields = {
        TotalAmount: order.total,
        TradeDesc: 'Miracode',
        ItemName: "合計共#{order.cart.total_quantity}件商品",
        ReturnURL: notifications_url, # 付款完成通知回傳網址
        ClientBackURL: order_url(order),
        ChoosePayment: payment_type[order.payment_id-1]
      }

      # ATM=3 額外增加的欄位
      if order.payment_id == 3
        fields[:PaymentInfoURL] = atm_payment_infos_url
      end
      
      @params = client.generate_checkout_params(fields) 
      order.update_attributes(merchant_trade_no: @params[:MerchantTradeNo])
      return @params
    end    

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_links.html.erb
<!-- 
	1 = 尚未付款
	2 = 已付款
	3 = 已出貨
	4 = 取消訂單
	5 = 取號成功
 -->
<% if order.pending? %>
	<%= link_to '取消此訂單', admin_order_path(order, change_status: 'cancel'), method: :put, remote: true, data: { confirm: "確定取消此訂單嗎？" }, class: "btn bg-maroon btn-xs" %>
<% end %>

<% if order.paid? %>
	<%= link_to '更新為已出貨', admin_order_path(order, change_status: 'shipped'), method: :put, remote: true, data: { confirm: "將訂單狀態更新為'已出貨'嗎？" }, class: "btn bg-orange btn-xs" %>
<% end %>

<% if order.shipped? %>
	<%= link_to '恢復為已付款', admin_order_path(order, change_status: 'paid'), method: :put, remote: true, data: { confirm: "將訂單狀態恢復為'已付款'嗎？" }, class: "btn bg-olive btn-xs" %>
<% end %>

app/views/admin/orders/edit.html.erb
<h1>Admin::Orders#edit</h1>
<p>Find me in app/views/admin/orders/edit.html.erb</p>

app/views/admin/orders/index.html.erb
<div id="page-wrapper">
  <div class="container-fluid">

    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
        <%=
	        case params[:status]
	        	when 'pending_orders' then "訂單 - 尚未付款"
	        	when 'paid_orders' then "訂單 - 已付款"
	        	when 'shipped_orders' then "訂單 - 已出貨"
	        	when 'cancel_orders' then "訂單 - 取消訂單"
	        	else "訂單列表"
	        end
        %>
        </h1>

        <div class="box">
          <div class="box-header">

          </div>

          <div class="box-body">
            <table class="table table-striped table-bordered">
              <thead>
              	<tr>
              		<th colspan="10">選擇訂單狀態：              		
              			<% OrderStatus.all.each do |status| %>
	                    <%= link_to admin_orders_path(status: status.get_query_params) do 
	                    	raw status.color_name
	                     end %>
	                     &nbsp;            				
              			<% end %>              		
              		</th>
              	</tr>
                <tr class="info">
                  <th width="5%">#</th>                  
                  <th width="15%">訂單編號</th>                  
                  <th width="8%">訂購人</th>
                  <th width="8%">訂購金額</th>
                  <th width="8%">付款方式</th>
                  <th width="8%">訂單狀態</th>
                  <th width="15%">訂購時間</th>
                  <th width="15%">付款時間</th>
                  <th width="8%">訂單明細</th>
                  <th width="10%">變更訂單狀態</th>
                </tr>
              </thead>

              <tbody>
                <% @orders.each do |order| %>
                <tr>
                  <td><%= order.id %></td>
                  <td>
                    <%= link_to [:admin, order] do
                      raw order.color_merchant_trade_no
                    end %>
                  </td>
                  <td><%= order.user.name %></td>
                  <td><%= order.total %></td>
                  <td><%= order.payment.name %></td>
                  <td>
                    <%= link_to admin_orders_path(status: order.order_status.get_query_params) do
                    	raw order.order_status.color_name
                     end %>
                  </td>
                  <td><%= l(order.created_at, format: :long) %></td>
                  <td><%= l(order.get_payment_time, format: :long) if order.paid? || order.shipped? %></td>
                  <td><%= link_to '訂單明細', [:admin, order], class: "btn bg-purple btn-xs"%></td>
                  <td>
                    <%= render 'links', order: order %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>

          <div class="box-footer clearfix">
          <%= paginate @orders %>
          </div>

        </div>

      </div>
    </div>
    <!-- /.row -->  

  </div>
  <!-- /.container-fluid -->

</div>

app/views/admin/orders/new.html.erb
<h1>Admin::Orders#new</h1>
<p>Find me in app/views/admin/orders/new.html.erb</p>

app/views/admin/orders/show.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">訂單明細</h1>
        <div class="box">



          <div class="box-body">
            <table class="table table-bordered">
              <thead>
              	<tr class="warning">
              		<th>訂單編號</th>
              		<td><%= raw @order.color_merchant_trade_no %></td>
              	</tr>

              	<tr class="success">
              		<th>訂單資訊</th>
              	</tr>

                <tr class="info" >
                  <th width="10%">ID</th>
                  <th width="18%">訂購時間</th>
                  <th width="18%">付款方式</th>
                  <th width="18%">訂單金額</th>
                  <th width="18%">訂購人</th>
                  <th width="18%">訂單狀態</th>

                </tr>
              </thead>

              <tbody>
                <tr>
                  <td><%= @order.id %></td>
                  <td><%= l(@order.created_at, format: :long) %></td>
                  <td><%= @order.payment.name %></td>
                  <td><%= @order.total %></td>                  
                  <td><%= @order.user.name %></td>                                                
                  <td><%= @order.order_status.name %></td>
                </tr>
              </tbody>
            </table>
          </div><!-- class="box-body" -->

          <div class="box-body">
            <table class="table table-bordered">
              <thead>
                <tr class="success">
              		<th>送貨資訊</th>
              	</tr>

                <tr class="info" >
                  <th width="10%">收貨人</th>
									<th width="18%">電話</th>
                  <th width="72%">地址</th>                  
                </tr>
              </thead>

              <tbody>
                <tr>
                  <td><%= @order.name %></td>
                  <td><%= @order.cellphone %></td>
                  <td><%= @order.address %></td>                                                                                                    
                </tr>
              </tbody>

            </table>
          </div><!-- class="box-body" -->

          <div class="box-body">
            <table class="table table-striped table-bordered">
              <thead>
                <tr class="success">
              		<th>商品資訊</th>
              	</tr>

                <tr class="info" >
                  <th width="10%"></th>
                  <th width="36%">商品名稱</th>
                  <th width="18%">單價</th>
                  <th width="18%">數量</th>
                  <th width="18%">商品總額</th>
                </tr>
              </thead>

              <tbody>
              	<% @order.cart.order_items.each_with_index do |item, index| %>
                <tr>
                  <td><%= index+1 %></td>
                  <td><%= item.product.name %></td>
                  <td><%= item.unit_price %></td>
                  <td><%= item.quantity %></td>                  
                  <td><%= item.total_price %></td>                                                                                   
                </tr>
                <% end %>
              </tbody>

              <tfoot>
              	<tr>
              		<td colspan="3"></td>
              		<th>運費</th>
              		<td><%= @order.shipping_fee %></td>              		
              	</tr>
              	<tr>
              		<td colspan="3"></td>
              		<th>訂單總額</th>
              		<td><%= @order.total %></td>
              	</tr>
              </tfoot>
            </table>
          </div><!-- class="box-body" -->

          <div class="box-footer clearfix">
          <%= link_to "回上一頁", :back, class: 'btn bg-olive ' %>
          </div>

        </div>

        </div>

      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>