config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  scope '(:locale)', locale: /en|zh-TW/ do
    root "pages#index"
    get "about"       => "pages#about"
    get "promotions"  => "event_categories#index"
    get "test"        => "pages#notify"
    get "search_product"      => "products#index"
    get "search_article"      => "articles#index"
    get "search_event"        => "events#index"

    resources :users

    resources :messages, only: [:new, :create]
    get "contact"   => "messages#new"

    resources :prod_categories, only: [:index, :show] do
      resources :products, only: [:show]
    end

    resources :blog_categories, only: [:index, :show] do
      resources :articles, only: [:show]
    end

    resources :event_categories, only: [:index, :show] do
      resources :events, only: [:show]
    end

    resources :comments, :notifications, :atm_payment_infos
    resources :orders, path_names: { new: 'checkout' }
    resources :carts, only: [:index]
    resources :order_items, only: [:create, :update, :destroy]
  end

  namespace :admin do
    root to: "orders#index"

    resources :prod_categories do
      resources :products
    end

    resources :blog_categories do
      resources :articles
    end

    resources :event_categories do
      resources :events
    end

    resources :company_profiles, :home_pages, :users, :orders
    resources :terms_of_services, :comments, :company_infos
  end

end

app/models/prod_category.rb
class ProdCategory < ActiveRecord::Base
	has_many :products, dependent: :destroy
	validates :name, presence: true
  #attr_accessible :name
end

app/controllers/admin/prod_categories_controller.rb
class Admin::ProdCategoriesController < Admin::BaseController 
  
  def index
    @categories = ProdCategory.all
  end

  def show
    @prod_category = ProdCategory.find(params[:id])
    @products = @prod_category.products
  end

  def new
    @prod_category = ProdCategory.new
  end

  def create
    @prod_category = ProdCategory.new(prod_category_params)
    if @prod_category.save
      redirect_to admin_prod_categories_url
    else
      render :new
    end
  end

  def edit
    @prod_category = ProdCategory.find(params[:id])    
  end

  def update
    @prod_category = ProdCategory.find(params[:id])
    if @prod_category.update_attributes(prod_category_params)
      redirect_to admin_prod_categories_url
    else
      render :edit
    end
  end

  def destroy
    @prod_category = ProdCategory.find(params[:id])
    @prod_category.destroy
    redirect_to admin_prod_categories_url
  end

  private

    def prod_category_params
      params.require(:prod_category).permit(:name, :language)
    end
end

app/controllers/prod_categories_controller.rb
class ProdCategoriesController < ApplicationController
  before_action :current_language_product_categories

  def index

  end

  def show    
    product_category = @prod_categories.find_by_id(params[:id])
    if product_category
      @products = product_category.products.on_sale
    else
      redirect_to prod_categories_url(locale: I18n.locale)
    end
  end

end

app/helpers/admin/prod_categories_helper.rb
module Admin::ProdCategoriesHelper
end

app/helpers/prod_category_helper.rb
module ProdCategoryHelper
end

app/views/admin/prod_categories/_fields.html.erb
<%= form_for [:admin, @prod_category], html: { role: "form" } do |f| %>
  <div class="box-body">

    <%= render 'admin/shared/error_messages', object: @prod_category %>          

    <div class="form-group">
      <%= f.label :name, "分類名稱" %>
      <%=f.text_field :name, placeholder: "Name", class: "form-control" %>
    </div>

    <div class="form-group">
      <%= label_tag "設定文章語言" %>
      <div class="radio">          
        <label>             
        <%= f.radio_button :language, "zh-TW" %>
        <%= f.label :language, "中文", value: "zh-TW" %>
        </label>  
      </div>
      <div class="radio">  
        <label> 
        <%= f.radio_button :language, "en" %>
        <%= f.label :language, "英文", value: "en" %>
        </label>
      </div>
    </div>

  </div>

  <div class="box-footer">
    <button type="submit" class="btn btn-danger">送出</button>
    <%= link_to "返回上一頁", :back, class: "btn btn-primary" %>
  </div>
  
<% end %>

app/views/admin/prod_categories/edit.html.erb
<% breadcrumb :edit_product_category, @prod_category %>

<section class="content">

  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">

        <div class="box-header with-border">
          <h3 class="box-title"> 重新命名商品分類</h3>
        </div>      

        <%= render 'fields' %>

      </div><!-- /.box -->
    </div>
  </div>

</section><!-- /.content -->

app/views/admin/prod_categories/index.html.erb
<% breadcrumb :product_category_list %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header with-border">
          <%= link_to new_admin_prod_category_path, class: "btn btn-danger btn-sm" do %>
            <li class="fa fa-fw fa-plus-square"></li> 建立新分類
          <% end %>
        </div>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>ID</th>
              <th>分類名稱</th>
              <th>語言</th>
              <th>商品數</th>
              <th>更新時間</th>
              <th>建立時間</th>
              <th>管理</th>
            </tr>

            <% @categories.each do |category| %>
            <tr>
              <td><%= category.id %></td>
              <td><%= link_to category.name, admin_prod_category_path(category) %></td>
              <td><%= translate_language_name(category.language) %></td>
              <td><%= category.products_count %></td>              
              <td><%= l(category.updated_at, format: :long) %></td>
              <td><%= l(category.created_at, format: :long) %></td>
              <td>
                <%= link_to "修改名稱", edit_admin_prod_category_path(category), class: "btn btn-primary btn-xs" %>
                <%= link_to "刪除此分類", [:admin, category], method: :delete, data: { confirm: "刪除此分類會同時刪除該分類底下的所有商品喔！" }, class: "btn btn-warning btn-xs" %>
              </td>
            </tr>
            <% end %>

            <!--
              <td><span class="label label-success">Approved</span></td>
              <td><span class="label label-warning">Pending</span></td>
              <td><span class="label label-primary">Approved</span></td>
              <td><span class="label label-danger">Denied</span></td>
            -->
          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div>
  </div>

app/views/admin/prod_categories/new.html.erb
<% breadcrumb :new_product_category %>

<section class="content">

  <div class="row">
    <div class="col-md-6">
      <div class="box box-primary">

        <div class="box-header with-border">
          <h3 class="box-title"> 新增商品分類</h3>
        </div>      

        <%= render 'fields' %>

      </div><!-- /.box -->
    </div>
  </div>

</section><!-- /.content -->

app/views/admin/prod_categories/show.html.erb
<% breadcrumb :single_product_category, @prod_category %>

<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">

        <div class="box-header with-border">
          <%= link_to new_admin_prod_category_product_path(@prod_category), class: "btn btn-danger btn-sm" do %>
            <li class="fa fa-fw fa-plus-square"></li> 建立新商品
          <% end %>
          <%= link_to "返回上一頁", :back, class: "btn btn-primary btn-sm" %>
        </div>

        <div class="box-body table-responsive no-padding">
          <table class="table table-hover">
            <tr>
              <th>ID</th>
              <th>首頁產品圖</th>
              <th>商品名稱</th>
              <th>商品狀態</th>
              <th>商品編號</th>
              <th>原價</th>
              <th>售價</th>              
              <th>更新時間</th>
              <th>建立時間</th>
              <th>管理</th>
            </tr>
            
            <% @products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td>
                <%= link_to [:admin, product.prod_category, product] do %>
                  <%= image_tag product.home_image_url, class: "img-thumbnail", width: "100", height: 'auto' %>
                <% end %>
              </td>              
              <td><%= link_to product.name, admin_prod_category_product_path(product.prod_category, product) %></td>
              <td><%= product.active? ? "販售中" : "已下架" %></td>
              <td><%= product.part_number %></td>
              <td><%= product.original_price %></td>
              <td><%= product.selling_price %></td>
              <td><%= l(product.updated_at, format: :long) %></td>
              <td><%= l(product.created_at, format: :long) %></td>              
              <td>
              <%= link_to "編輯", edit_admin_prod_category_product_path(product.prod_category, product) %>
              <%= link_to "刪除", [:admin, product.prod_category, product], method: :delete, data: { confirm: "確定刪除這個商品嗎？" } %>
              </td>
            </tr>
            <% end %>
            

            <!--
              <td><span class="label label-success">Approved</span></td>
              <td><span class="label label-warning">Pending</span></td>
              <td><span class="label label-primary">Approved</span></td>
              <td><span class="label label-danger">Denied</span></td>
            -->
          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->
    </div>
  </div>
<!-- @categories -->
</section>